version: '3'

services:
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "8090:8090"
  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:4200"
  