version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: ingsw3
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root","-p root"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./frontend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4200:4200"
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"