version: '3'

services:
  db:
    container_name: db
    build: ./db
    image: ingsw3
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ingsw3
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p root"
        ]
      timeout: 20s
      retries: 10
  backend:
    container_name: backend
    build: ./backend
    restart: on-failure
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200"
