version: '3'

services:
  frontend:
    build: ./frontend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4200:4200"
  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"