version: '3'

services:
  db:
    container_name: db
    build: ./db
    image: ingsw3
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ingsw3
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p root"
        ]
      timeout: 20s
      retries: 10

  cloudsqlproxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy -dir=/cloudsql -instances=ingsw3-428221:us-central1:ingsw3=tcp:3306 -credential_file=/config/credentials.json
    volumes:
      - ./credentials.json:/config/credentials.json

  backend:
    container_name: backend
    build: ./backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      cloudsqlproxy:
        condition: service_started

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200"
