name: CI/CD worflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build images
      run: |
        docker-compose build

    - name: start containers
      run: |
        docker-compose up -d
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Dependencies
      run: go mod download

    - name: Stop containers
      run: |
        docker-compose down

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag images
      run: |
        docker tag ingsw3final_backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker tag ingsw3final_frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag ingsw3:latest ${{ secrets.DOCKERHUB_USERNAME }}/db:latest
      
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/db:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH  }}
        project_id: ingsw3-428221
        export_default_credentials: true

    - name: Configure Docker for Container Registry
      run: |
        gcloud auth configure-docker

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Download Docker images
      run: |
        docker pull matiaslessioucc/backend:latest
        docker pull matiaslessioucc/frontend:latest
        docker pull matiaslessioucc/db:latest
    
    - name: Run Docker db container to extract SQL file
      run: |
        docker create --name temp-container matiaslessioucc/db:latest
        docker cp temp-container:/docker-entrypoint-initdb.d/ingsw3.sql ./ingsw3.sql
        docker rm temp-container

    - name: Upload SQL file to Cloud Storage
      run: gsutil cp ./ingsw3.sql gs://ingsw3

    - name: Tag backend and frontend Docker images
      run: |
        docker tag matiaslessioucc/backend:latest gcr.io/ingsw3-428221/backend:latest
        docker tag matiaslessioucc/frontend:latest gcr.io/ingsw3-428221/frontend:latest

    - name: Push backend and frontend Docker images to Google Container Registry
      run: |
        docker push gcr.io/ingsw3-428221/backend:latest
        docker push gcr.io/ingsw3-428221/frontend:latest
        
    - name: Import SQL file to Cloud SQL
      run: |
        gcloud config set project ingsw3-428221
        gcloud --quiet sql import sql ingsw3 gs://ingsw3/ingsw3.sql
    - name: Deploy frontend to Google Cloud Run
      run: |
        gcloud run deploy frontend \
         --image gcr.io/ingsw3-428221/frontend:latest \
         --port=4200 \
         --platform managed \
         --region=us-central1 \
         --allow-unauthenticated \
         --max-instances=15

    - name: Deploy backend and frontend to Google Cloud Run
      run: |
        gcloud run deploy backend \
        --image gcr.io/ingsw3-428221/backend:latest \
        --port=8080 \
        --platform managed \
        --region=us-central1 \
        --allow-unauthenticated \
        --max-instances=15 \
        --add-cloudsql-instances=ingsw3-428221:us-central1:ingsw3 \
        --set-env-vars=DB_HOST=34.31.144.174,DB_PORT=3306,DB_NAME=ingsw3,DB_USER=root,DB_PASS=root
        